apps/home/urls.py
from django.urls import path
from .views import *
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'navabrs_rest', NavbarViewSet)

app_name = 'domain'
urlpatterns = [
    path('',index),
    path('pages',Blogs.as_view(),name='blogs'),
    # path('pages/detail/<slug:slug>', BlogDetail.as_view(), name='blog-detail'),
    path('pages/<str:group>/detail/<slug:slug>',BlogDetail.as_view(),name='blog-detail'),
] +router.urls

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [

    path('',include('apps.home.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

domain/models.py
# from turtle import title
from django.utils import timezone
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

PAGE_TYPES_CHOICES = [
    (0, "اخبار"),
    (1, "اطلاعیه ها"),
    (2, "مطالب آموزشی"),
    (4, "درباره ما"),
    (5, "تماس با ما"),
    (6, "سایر"),
]

COMPANY_TYPES_CHOICES = [
    (0, "تعاونی روستایی"),
    (1, "تعاونی کشاورزی"),
    (2, "تعاونی تولید "),
    (3, "اتحادیه تعاونی روستایی"),
    (4, "اتحادیه تعاونی تولید"),
    (5, "نظام صنفی"),
]

POST_TYPES_CHOICES = [
    (0, "مدیر عامل"),
    (1, "رئیس هیأت مدیره"),
    (2, "نائب رئیس هیأت مدیره"),
    (3, "هیأت مدیره (اصلی)"),
    (4, "هیأت مدیره (علل بدل)"),
    (5, "بازرس"),
    (6, "حسابدار"),
]

ACTIVITY_STATUS_CHOICES = [
    (0, "فعال"),
    (1, "غیرفعال"),
]


class Tag(models.Model):
    title = models.CharField(max_length=100, unique=True,verbose_name="عنوان")
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'برچسب'
        verbose_name_plural = 'برچسب'


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True,verbose_name="عنوان")
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="children", blank=True, null=True, verbose_name="والد"
    )
    cover = models.ImageField(
        upload_to="images/pages", verbose_name="عکس کاور"
    )
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی'


class PageGroup(models.Model):
    title = models.CharField(max_length=100, unique=True,verbose_name="عنوان")
    type = models.PositiveSmallIntegerField(choices=PAGE_TYPES_CHOICES,verbose_name="نوع")
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'گروه بندی صفحه'
        verbose_name_plural = 'گروه بندی صفحه'
        
        
class Page(models.Model):
    title = models.CharField(max_length=450,verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات")
    slug = models.SlugField(max_length=200, unique=True,verbose_name="اسلاگ")
    category = models.ForeignKey(Category, on_delete=models.CASCADE,related_name='pages',verbose_name="دسته بندی")
    tags = models.ManyToManyField(Tag,related_name='pages',verbose_name="برچسب")
    content = RichTextField(verbose_name="بدنه صفحه")
    page_group = models.ForeignKey(PageGroup, on_delete=models.CASCADE,verbose_name="گروه صفحه")
    cover = models.ImageField(
        upload_to="images/pages",verbose_name="عکس کاور"
    )
    published_at = models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True,verbose_name="وضعیت")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'صفحه'
        verbose_name_plural = 'صفحهات'


class Navbar(models.Model):
    title = models.CharField(max_length=100, unique=True,verbose_name="عنوان")
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="children", blank=True, null=True,verbose_name="والد"
    )
    is_active = models.BooleanField(
        default=False,verbose_name="فعال یاشد؟"
    )
    is_megamenu = models.BooleanField(
        default=False,verbose_name="از نوع مگامنو باشد؟"
    )
    is_internal_link = models.BooleanField(default=True,verbose_name="لینک خارجی است؟")
    link = models.URLField(null=True, blank=True,verbose_name="لینک")
    page = models.ForeignKey(Page, on_delete=models.CASCADE, null=True, blank=True,verbose_name="انتخاب صفحه")
    is_open_new_tab_browser = models.BooleanField(default=False,verbose_name="باز شدن در تب جدید")
    position = models.SmallIntegerField(null=True, blank=True)
    icon = models.CharField(max_length=100,blank=True,null=True, verbose_name='آیکن')
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'منو'
        verbose_name_plural = 'منوا'

    def get_json(self):
        return {
            'id': self.id,
            'title': self.title,
            'children': [{'id': b.id, 'title': b.title} for b in self.children.all()]}


class Slider(models.Model):
    title = models.CharField(max_length=150, null=True, blank=True, verbose_name='عنوان')
    description = models.CharField(max_length=350, null=True, blank=True, verbose_name='توضیحات')
    page = models.ForeignKey(Page, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='صفحه')
    image = models.ImageField(upload_to="images/slider", verbose_name='تصویر')
    is_external_link = models.BooleanField(default=False, verbose_name='لینک خارجی')
    link = models.URLField(null=True, blank=True, verbose_name='لینک')
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'اسلایدر'
        verbose_name_plural = 'اسلایدر'


class Services(models.Model):
    title = models.CharField(max_length=150, null=True, blank=True, verbose_name='عنوان')
    description = models.CharField(max_length=350, null=True, blank=True, verbose_name='توضیحات')
    icon = models.CharField(max_length=100, verbose_name='آیکن', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'خدمات'
        verbose_name_plural = 'خدمات'


class CompanyMember(models.Model):
    type = models.PositiveSmallIntegerField(choices=POST_TYPES_CHOICES,verbose_name="سمت")
    name = models.CharField(max_length=150, null=True, blank=True, verbose_name='نام')
    mobile_number = models.PositiveSmallIntegerField(verbose_name="شماره همراه")
    registry_date = models.DateTimeField(auto_now=True,verbose_name="تاریخ عضویت")
    company = models.ForeignKey('Company',on_delete=models.SET_NULL,blank=True,null=True,verbose_name='شرکت')
    status = models.PositiveSmallIntegerField(choices=ACTIVITY_STATUS_CHOICES,verbose_name="وضعیت")
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'عضو'
        verbose_name_plural = 'اعضاء'


class Company(models.Model):
    title = models.CharField(max_length=250, verbose_name='عنوان')
    description = models.CharField(max_length=500, verbose_name='توضیحات')
    type = models.PositiveSmallIntegerField(choices=COMPANY_TYPES_CHOICES, verbose_name="نوع شرکت")
    date_of_build = models.PositiveSmallIntegerField(verbose_name="تاریخ ساخت", null=True, blank=True)
    register_number = models.PositiveSmallIntegerField(verbose_name="شماره ثبت", null=True, blank=True)
    national_code = models.PositiveIntegerField(verbose_name="شماره شناسه ملی", null=True, blank=True)
    economic_code = models.PositiveIntegerField(verbose_name="کد اقتصادی", null=True, blank=True)
    phone_number = models.PositiveSmallIntegerField(verbose_name="تلفن ثابت", null=True, blank=True)
    member_count = models.PositiveSmallIntegerField(verbose_name="تعداد اعضاء", null=True, blank=True)
    village_count = models.PositiveSmallIntegerField(verbose_name="تعداد روستاهای حوزه عمل", null=True, blank=True)
    oil_position_count = models.PositiveSmallIntegerField(verbose_name="تعداد جایگاه مواد نفتی", null=True, blank=True)
    fuel_store_count = models.PositiveSmallIntegerField(verbose_name="تعداد فروشندگی های سوخت", null=True, blank=True)
    last_fund_count = models.PositiveSmallIntegerField(verbose_name="تعداد سهام و آخرین سرمایه ثبتی", null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=ACTIVITY_STATUS_CHOICES,verbose_name="وضعیت شرکت", null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'شرکت'
        verbose_name_plural = 'شرکت ها'


class ExternalLink(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان')
    url = models.URLField(verbose_name='لینک')
    created_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'لینک خارجی'
        verbose_name_plural = 'لینک خارجی'


class Comment(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام نام خانوادگی')
    description = models.CharField(max_length=500)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    phone_number = models.PositiveIntegerField(verbose_name="شماره همراه", null=True, blank=True)
    email = models.EmailField(verbose_name="آدرس الکترونیکی", null=True, blank=True)

apps/home/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework import permissions,viewsets
from domain.serializers import *
from django.views.generic import ListView,DetailView
from domain.models import *


def index(request):
   # navbars = NavbarsSerializer(Navbar.objects.filter(parent__isnull=True), many=True).data
   # navbars = list(navbars)
   sliders = Slider.objects.all()
   services = Services.objects.all()
   last_news = Page.objects.filter(page_group__type=0).all()[:10]
   last_notification = Page.objects.filter(page_group__type=1).all()[:5]
   return render(request,"home/index.html",context={
       'sliders':sliders,
       'services':services,
       'last_news':last_news,
       'last_notification':last_notification
   })


class NavbarViewSet(viewsets.ModelViewSet):
    queryset = Navbar.objects.filter(parent__isnull=True)
    serializer_class = NavbarsSerializer


class Blogs(ListView):
    model = Page
    queryset = Page.objects.all()
    template_name = 'home/blogs.html'
    paginate_by = 5
    ordering = '-created_at'
    extra_context = {
        'categories':Category.objects.all(),
        'last_blogs':Page.objects.order_by('-created_at')[:5],
        'tags':Tag.objects.all()[:5],
    }


class BlogDetail(DetailView):
    model = Page
    template_name = 'home/detail.html'
    extra_context = {
        'categories':Category.objects.all(),
        'last_blogs':Page.objects.order_by('-created_at')[:5],
        'tags':Tag.objects.all()[:5],
    }

templates/home/blogs.html
{% extends 'base.html' %}
{% block content %}
        <section class="container mt-4 mb-2">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb radius15 shadow-sm">
                        <ul>
                            <li><a href="#">خانه / </a></li>
                            <li><a href="#" class="current">مسیر جاری</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <section class="container mb-4">
            <div class="row">
                <div class="col-xl-3 order-xl-0 order-1 mb-4">
                    <div class="card pcountry cati p-3 mb-3">
                        <div class="d-flex flex-row justify-content-between bg-light py-2 px-4 my-2 bright radius15">
                            <h2>دسته بندی ها</h2>
                            <a href="#">- بیشتر -</a>
                        </div>
                        <ul class="list-unstyled">
                            {% for category in categories %}
                            <li><a href="#"><img src="{{ category.cover.url }}" class="ml-2" /><span>{{ category.title }} ({{ category.pages.all|length }})</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card thumb-post p-3 mb-3">
                        <h2 class="bg-light py-2 px-4 mt-2 mb-4 bright radius15">آخرین مطالب</h2>
                        <ul class="fa12">
                            {% for last_blog in last_blogs %}
                                                            <li>
                                <div class="d-flex flex-row">
                                    <a href="#"><img src="{{ last_blog.cover.url }}" /></a>
                                    <div class="m-2">
                                        <p><a href="#">{{ last_blog.title }}</a></p>
                                        <span>{{ last_blog.created_at }}</span>
                                    </div>
                                </div>
                            </li>

                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card pcolor  p-3 mb-3">
                        <h2 class="bg-light py-2 px-4 my-2 bright radius15">برچسب ها</h2>
                        <ul>
                            {% for tag in tags %}
                            <li><a href="#">{{ tag.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-xl-9  order-xl-1 order-0 mb-4">
                            <div class="row">
                                {% for blog in object_list %}
                                <div class="col-lg-4 col-sm-6 mb-4">
                                    <div class="card">
                                        <a href="blog_destails.html"><img class="card-img-top" style="height: 200px" src="{{ blog.cover.url }}" alt="Card image"></a>
                                        <div class="card-body">
                                            <h2 class="IRANSans_Bold"><a href="blog_destails.html">{{ blog.title }}</a></h2>
                                            <span class="text-primary fa12 IRANSans_Medium"><a href="#">{{ blog.category.title }}</a></span>
                                            <p>
                                               {{ blog.description }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                    <div class="row mt-3">

                        <div class="col-12 text-center mx-auto">
                            <ul class="pagination  justify-content-center">
                                 {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">«</a></li>
                                {% endif %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                                {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">»</a></li>
                            {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

templates/home/detail.html
{% extends 'master.html' %}
{% block content %}

        <section class="container mt-4 mb-2">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb radius15 shadow-sm">
                        <ul>
                            <li><a href="{% url 'domain:blogs' %}">خانه / </a></li>
                            <li><a href="#" class="current"> {{ object.title }}</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>


        <section class="container mb-4">
            <div class="row">
                <div class="col-xl-3 order-xl-0 order-1 mb-3">

                    <div class="card pcountry cati  p-3 mb-3">
                        <div class="d-flex flex-row justify-content-between bg-light py-2 px-4 my-2 bright radius15">
                            <h2>دسته بندی ها</h2>
                            <a href="#">- بیشتر -</a>
                        </div>

                        <ul class="list-unstyled">
                            {% for category in categories %}
                            <li><a href="#"><img src="{{ category.cover.url }}" class="ml-2" /><span>{{ category.title }} ({{ category.pages.all|length }})</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card thumb-post p-3 mb-3">
                        <h2 class="bg-light py-2 px-4 mt-2 mb-4 bright radius15">آخرین مطالب</h2>
                        <ul class="fa12">
                            {% for last_blog in last_blogs %}
                                                            <li>
                                <div class="d-flex flex-row">
                                    <a href="#"><img src="{{ last_blog.cover.url }}" /></a>
                                    <div class="m-2">
                                        <p><a href="#">{{ last_blog.title }}</a></p>
                                        <span>{{ last_blog.created_at }}</span>
                                    </div>
                                </div>
                            </li>

                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card pcolor  p-3 mb-3">
                        <h2 class="bg-light py-2 px-4 my-2 bright radius15">برچسب ها</h2>
                        <ul>
                            {% for tag in tags %}
                            <li><a href="#">{{ tag.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-xl-9  order-xl-1 order-0 mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h2>نمایش <span class="text-primary">جزئیات</span></h2>
                        </div>
                        <div class="card-body p-sm-4">
                            <div class="item mb-4">

                                <div class="row">
                                    <div class="col-lg-12 mb-3 text-justify ">
                                        <a href="#" class="mb-3"><h2>{{ object.title }}</h2></a>
                                        <img src="{{ object.cover.url }}" alt="" class="img-fluid my-4 blogimg radius15" />
                                        <p>{{ object.content|safe }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="float-left">
                                            <a class="btn bg-light py-1 px-4 m-1 fa12 radius25" href="#"><i class="fal fa-share"></i></a>
                                            <a class="btn bg-light py-1 px-4 m-1 fa12 radius25" href="#"><i class="fal fa-share-alt"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="comment p-md-3 mt-3">
                                            <h6 class="IRANSans-Bold pl-2 ml-3 IRANSansWeb_Medium">ارسال دیدگاه :</h6>
                                            <img src="Img/avatar.jpg" class="img-fluid my-2 rounded-circle">
                                            <div class="form-group">
                                                <input class="form-control w-75 mb-3" type="text" placeholder="نـام">
                                                <input class="form-control w-75 mb-3" type="email" placeholder="ایـمیل">
                                                <textarea class="form-control area" cols="60" rows="9" placeholder="دیدگاه" style="height: 150px!important"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-warning">ارسـال<i class="fal fa-paper-plane mr-2"></i> </button>
                                        </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

templates/home/index.html
{% extends 'master.html' %}
{% load jalali_tags %}

{% block content %}
    <!-- start slider -->
        <section class="container pt-2 p_relative">
            <div class="row">
                <div class="col-lg-12 p-0 mb-3">
                    <div id="owl-mainslider" class="owl-carousel owl-theme text-center">
                        {% for slider in sliders %}
                            <div class="item">
                                <a href="{% url 'domain:blog-detail' slider.page.page_group.get_type_display slider.page.slug %}">
                                    <img src="{{ slider.image.url }}" class="radius15 img-fluid w-100" />
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    <!-- end slider -->

    <!-- start service -->
    {% if services %}
            <div class="container p-lg-4 p-3 card my-2 Service-purp">
            <h3 class="my-3 bt-center IRANSansWeb_Medium text-center">خدمات ما</h3>
            <div class="row">
                {% for service in services %}
                    <div class="col-md-4 p-3">
                    <div class="p-3 d-flex flex-lg-row flex-md-column text-lg-right text-md-center mb-4 service_style">
                        <div class="icon ml-lg-3 mb-3">
                            <i class="fal {{ service.icon }} fa-2x p-3"></i>
                        </div>
                        <div>
                            <h2>{{service.title}}</h2>
                            <p>{{service.description}} </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <!-- end service -->

    <!-- start last news -->
        <section class="container">
            <h3 class="bt-center text-center mb-4">آخرین اخبار ما</h3>
            <div id="owl-toparticle" class="owl-carousel owl-theme text-right ">
                {% for last_new in last_news %}
                    <div class="card m-2 radius15">
                        <a href="{% url 'domain:blog-detail' last_new.page_group.get_type_display last_new.slug %}"><img class="card-img-top" src="{{ last_new.cover.url }}" alt="Card image"></a>
                        <div class="card-body">
                            <div class="d-flex flex-row justify-content-between mb-2">
                                <span class="fa12"><i class="fal fa-user ml-2 text-info"></i>{{ request.user }}</span>
                                <span class="fa12"><i class="fal fa-clock ml-2 text-info"></i>{{ last_new.created_at }}</span>
                            </div>
                            <a href="{% url 'domain:blog-detail' last_new.page_group.get_type_display last_new.slug %}"><h2 class="IRANSans_Medium mb-2">{{ last_new.title }}</h2></a>
                            <p>{{ last_new.description }}</p>
                            <a href="{% url 'domain:blog-detail' last_new.page_group.get_type_display last_new.slug %}" class="btn btn-link mt-2">ادامه مطلب<i class="fal fa-chevron-left mr-2"></i></a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>

    <!-- end last news -->



    <!-- start category news -->

            <section class="container my-4">
            <div class="row">
                <div class="col-xl-6 mb-4">
                    <div class="card">
                        <div class="card-header d-flex flex-row justify-content-between">
                            <h2>اطلاعیه ها</h2>
                            <a href="#">- بیشتر -</a>
                        </div>
                        <div class="card-body tejarat pcu">
                            <div class="table-responsive">
                                <table class="table table-striped fa-12">
                                    <tbody>
                                    {% for item in last_notification %}
                                        <tr>
                                            <th>
                                                <img src="{{ item.cover.url }}" class="img-fluid ml-1 mb-1" alt="">
                                                <a href="{% url 'domain:blog-detail' item.page_group.get_type_display item.slug %}">{{ item.title }}</a>
                                            </th>
                                            <td>{{ item.created_at|to_jalali:'%y/%m/%d _ %H:%M:%S'}}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-xl-6 mb-4">
                    <div class="card">
                        <div class="card-header d-flex flex-row justify-content-between">
                            <h2>مطالب آموزشی</h2>
                            <a href="#">- بیشتر -</a>
                        </div>
                        <div class="card-body latestProduct p-3">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <div class="d-flex flex-row">
                                        <img src="Img/cati/img_1.jpg" alt="">
                                        <div class="mr-2">
                                            <a href="#">لورم ایپسوم متن ساختگی با سادگی</a>
                                            <span>دسته بندی : تغذیه</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="d-flex flex-row">
                                        <img src="Img/cati/img_1.jpg" alt="">
                                        <div class="mr-2">
                                            <a href="#">لورم ایپسوم متن ساختگی با سادگی</a>
                                            <span>دسته بندی : علوم اقتصاد</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!-- end category news -->

{% endblock %}